# Generated by Django 3.0.5 on 2021-05-15 20:08

import app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timezone', models.CharField(max_length=25)),
                ('timezone_offset', models.IntegerField()),
                ('current', djongo.models.fields.EmbeddedField(model_container=app.models.WeatherData)),
                ('hourly', djongo.models.fields.ArrayField(model_container=app.models.WeatherData)),
            ],
        ),
    ]
